<template>
  <Layout :title="$page.project.title">
    <article class="project-post">
      <g-image
        class="thumnail"
        :src="$page.project.thumbnail"
        :alt="$page.project.title"
      />
      <ProjectMeta
        :title="$page.project.title"
        :categories="$page.project.categories"
        :year="$page.project.year"
      />
      <div class="content" v-html="$page.project.content" />
    </article>
  </Layout>
</template>

<page-query>
query Project ($path: String!) {
  project: project(path: $path) {
    title
    thumbnail
    year
    categories
    content
  }
}
</page-query>

<script>
import ProjectMeta from "@/components/ProjectMeta";

export default {
  components: {
    ProjectMeta
  },
  mounted() {
    // Instead of checking for firstChild nodes that is text elements,
    // check and see if the p tags only contains img elements and that noscript
    // generated by Gridsome.
    const contentElements = document.querySelectorAll("p");
    contentElements.forEach(
      element =>
        element.firstChild.nodeName === "#text" &&
        element.classList.add("content-text")
    );
  }
};
</script>

<style lang="scss">
.project-post {
  padding: 0 2rem;
  margin-bottom: 8rem;
}
img {
  width: 100% !important;
  margin-bottom: 2rem;
  cursor: url(/uploads/orgngey.cur), auto;
}
p {
  margin: 0;
}
.content-text {
  padding: 2rem 0 3rem 0;
  font-size: 1.5rem;
  font-weight: 400;
  margin-left: 0;
  max-width: 780px;
  line-height: 2.5;
  @media (min-width: 920px) {
    margin-left: 60%;
  }
}
.rainbow {
    
   /* Chrome, Safari, Opera */
  -webkit-animation: rainbow 5s infinite; 
  
  /* Internet Explorer */
  -ms-animation: rainbow 5s infinite;
  
  /* Standar Syntax */
  animation: rainbow 5s infinite; 
}
/* Chrome, Safari, Opera */
@-webkit-keyframes rainbow{
  0%{color: orange;}	
  10%{color: purple;}	
	20%{color: red;}
  30%{color: CadetBlue;}
	40%{color: yellow;}
  50%{color: coral;}
	60%{color: green;}
  70%{color: cyan;}
  80%{color: DeepPink;}
  90%{color: DodgerBlue;}
	100%{color: orange;}
}
/* Internet Explorer */
@-ms-keyframes rainbow{
   0%{color: orange;}	
  10%{color: purple;}	
	20%{color: red;}
  30%{color: CadetBlue;}
	40%{color: yellow;}
  50%{color: coral;}
	60%{color: green;}
  70%{color: cyan;}
  80%{color: DeepPink;}
  90%{color: DodgerBlue;}
	100%{color: orange;}
}
/* Standar Syntax */
@keyframes rainbow{
    0%{color: orange;}	
  10%{color: purple;}	
	20%{color: red;}
  30%{color: CadetBlue;}
	40%{color: yellow;}
  50%{color: coral;}
	60%{color: green;}
  70%{color: cyan;}
  80%{color: DeepPink;}
  90%{color: DodgerBlue;}
	100%{color: orange;}
}

.container {
  position: relative;
  display: flex;
  flex-direction: column;
  min-height: 100vh;
}

/* Then style the iframe to fit in the container div with full height and width */
.responsive-iframe {
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  width: 100%;
  height: 100%;
}
</style>
